### ISSUE TITLE
Specify sign priority as a config item

### ISSUE THREAD

**Issue by olimorris** [andythigpen/nvim-coverage#1]
I have `lsp diagnostics` and `gitsigns` on my sign column. It would be great if I could priorities coverage above all of them.

<img width="817" alt="Screen Shot 2022-03-28 at 00 20 56@2x" src="https://user-images.githubusercontent.com/9512444/160305614-c7e62628-03e8-4850-acaf-7591b55cb280.png">

**Comment by andythigpen** [comment]
This should be possible using configuration like:
```lua
require("coverage").setup({
	signs = {
		covered = { priority = 100 }, -- use a higher value than diagnostics or gitsigns
		uncovered = { priority = 100 },
	},
})
```
