### ISSUE TITLE
Highlights doesn't work

### ISSUE THREAD

**Issue by ehsanonline** [andythigpen/nvim-coverage#11]
![err](https://user-images.githubusercontent.com/4243503/193433139-fc5d4a66-2172-4e53-9722-5819d82392cf.png)
it shows the correct summery of coverage, I used different signs and changed `fg`, `bg`, etc. colors, I disabled gitsigns, but none of them worked. not sure what is the problem.

**Comment by ehsanonline** [comment]
same result with pure neovim setup, I used Cmder and Alacritty :
Ubuntu 20.04
![1 (2)](https://user-images.githubusercontent.com/4243503/193463174-3f52a073-4007-4947-8011-e2104e09f8a3.png)
![1 (1)](https://user-images.githubusercontent.com/4243503/193463222-74fe0da0-83dd-4fe0-a12a-078e8782ef76.png)

**Comment by andythigpen** [comment]
* What are the outputs for `:hi CoverageCovered` and `:hi CoverageUncovered`?
* What `colorscheme` are you using?
* Is nvim-coverage loaded before or after the colorscheme is set? Many colorschemes will clear all highlights when loading.

Here's an example:
```
use({
  "andythigpen/nvim-coverage",
  after = "material.nvim", -- highlights are cleared unless this is after material.nvim
  requires = "nvim-lua/plenary.nvim",
  config = function()
    require("coverage").setup({})
  end,
})
```

**Comment by ehsanonline** [comment]
it's a clean neovim installation, no other plugins/configs. `after = "material.nvim",` didn't help. this is all my configs now :
```lua
return require('packer').startup(function(use)
use 'wbthomason/packer.nvim' 
use({                                         
  "andythigpen/nvim-coverage", 
  after = "material.nvim", 
  requires = "nvim-lua/plenary.nvim",
  config = function() 
    require("coverage").setup()
  end,  
})                                            
end) 
```
![1](https://user-images.githubusercontent.com/4243503/193467791-82bb80e5-bd9c-49ec-8d5e-b032365a080b.png)

**Comment by andythigpen** [comment]
The `after = "material.nvim"` line would only apply if you were using the material.nvim colorscheme. That was just an example from my config, so you can remove it.

Based on the output above, both highlight groups exist and are set. Is `termguicolors` disabled? Right now, nvim-coverage only sets `guifg`, `guibg`, etc. but if you can't use `termguicolors` then I could probably add a method of setting `ctermfg` and `ctermbg` instead.

**Comment by ehsanonline** [comment]
after installing a colorscheme (tokyonight) it worked.
```vim
lua require('plugins')
colorscheme tokyonight
```
```lua
return require('packer').startup(function(use)
use 'wbthomason/packer.nvim' 
use 'folke/tokyonight.nvim'
use({                                         
  "andythigpen/nvim-coverage", 
  requires = "nvim-lua/plenary.nvim",
  config = function() 
    require("coverage").setup()
  end,  
})                                            
end) 
```


![1](https://user-images.githubusercontent.com/4243503/193468806-7937cb1f-8a8e-4f70-9ce4-6e25bbecb4b6.png)

**Comment by cristobalgvera** [comment]
For those who are looking for a proper explanation...

This problem is caused due to the usage of `highlight clear`, a common practice used by colorscheme plugins in order to setup his colorscheme without any issue.

This is a problem if you setup this plugin (or any other that uses his own colorscheme configuration) before the plugin's colorscheme.

If you can't avoid this behavior using the workaround provided by @andythigpen e.g. because you are using a NeoVim framework, you can add an autocommand that handle it every time colorscheme change.

```lua
  vim.api.nvim_create_autocmd("ColorScheme", {
    desc = "Add nvim-coverage highlight",
    callback = function()
      vim.cmd([[
        hi CoverageCovered guifg=#b7f071
        hi CoverageUncovered guifg=#f07178
        hi CoveragePartial guifg=#aa71f0
        hi CoverageSummaryHeader gui=bold,underline guisp=fg
        hi! link CoverageSummaryBorder FloatBorder
        hi! link CoverageSummaryNormal NormalFloat
        hi! link CoverageSummaryCursorLine CursorLine
        hi! link CoverageSummaryPass CoverageCovered
        hi! link CoverageSummaryFail CoverageUncovered
      ]])
    end,
  })
```

There are lot of custom configuration that you can make based on this idea, this is just a solution that let's this plugin works using his default configuration.

**Comment by duncanam** [comment]
> For those who are looking for a proper explanation...
> 
> This problem is caused due to the usage of `highlight clear`, a common practice used by colorscheme plugins in order to setup his colorscheme without any issue.
> 
> This is a problem if you setup this plugin (or any other that uses his own colorscheme configuration) before the plugin's colorscheme.
> 
> If you can't avoid this behavior using the workaround provided by @andythigpen e.g. because you are using a NeoVim framework, you can add an autocommand that handle it every time colorscheme change.
> 
> ```lua
>   vim.api.nvim_create_autocmd("ColorScheme", {
>     desc = "Add nvim-coverage highlight",
>     callback = function()
>       vim.cmd([[
>         hi CoverageCovered guifg=#b7f071
>         hi CoverageUncovered guifg=#f07178
>         hi CoveragePartial guifg=#aa71f0
>         hi CoverageSummaryHeader gui=bold,underline guisp=fg
>         hi! link CoverageSummaryBorder FloatBorder
>         hi! link CoverageSummaryNormal NormalFloat
>         hi! link CoverageSummaryCursorLine CursorLine
>         hi! link CoverageSummaryPass CoverageCovered
>         hi! link CoverageSummaryFail CoverageUncovered
>       ]])
>     end,
>   })
> ```
> 
> There are lot of custom configuration that you can make based on this idea, this is just a solution that let's this plugin works using his default configuration.

This worked for me with LunarVim! Thanks.
