### ISSUE TITLE
Coverage signs are being added multiple times

### ISSUE THREAD

**Issue by LiveNL** [andythigpen/nvim-coverage#12]
As far as I could find, the coverage signs (lists) are being added multiple times (unintentionally?).

#### Steps to reproduce:
- Default install/config
- A vim signcolumn with a width larger than 1 (I'm using `vim.opt.signcolumn = 'auto:3-4'`)
- Started nvim-coverage with `require('coverage').load(true)`
- Ran python tests with pytest (to generate .coverage)
- Result: each time I run tests a list of signs is being added (up until the signcolumn width).

<img width="58" alt="image" src="https://user-images.githubusercontent.com/5443727/196040017-4402f636-6bff-405d-a6e5-4e8e7a83a5fc.png">

I'm not sure if there is another preferred way to start/run nvim-coverage that prevents this behaviour, but I'd like to change the behaviour. 

I've looked into the `load` function (in `init.lua`), which calls `signs.place` and `vim.fn.sign_placelist(signs)` (as `place` and `signs.is_enabled()` evaluate to true). `sign_placelist` only adds, and there seems to be no update function. Therefore to prevent the behaviour, `unplace` could/should be called. 

For me, to resolve the issue, adding `signs.unplace(config.opts.sign_group)` at ln 53 of `init.lua` seems to work. But, as mentioned, I'm not sure if this is how the issue should be resolved.

I'm happy to contribute my suggestion, but currently I'm not sure if this a desired change.

**Comment by andythigpen** [comment]
Thank you for the detailed report. I use a `signcolumn` width of 1 so I never really noticed this behavior, but it should hopefully be resolved now.

**Comment by LiveNL** [comment]
Great! Thanks for the quick response & update 👏
