### ISSUE TITLE
Python partial coverage

### ISSUE THREAD

**Issue by nymann** [andythigpen/nvim-coverage#14]
Hi @andythigpen 

Thanks for a great plugin!

It doesn't seem like partial coverage for python is supported atm:

![image](https://user-images.githubusercontent.com/7005867/206325029-a7f99454-f3f7-42f4-b550-10f204e0744b.png)

checked against:
![image](https://user-images.githubusercontent.com/7005867/206325124-d08a7763-5c7d-4591-93db-8d395af3bebc.png)

**Comment by andythigpen** [comment]
You're correct - that's not currently supported. I can look into what it would take to add it.

**Comment by nymann** [comment]
That would be brilliant!
