### ISSUE TITLE
Auto reload for projects that don't have coverage.out files yet 

### ISSUE THREAD

**Issue by a-h** [andythigpen/nvim-coverage#19]
## Setup

I've setup nvim-coverage with auto_reload.

```lua
local coverage = require("coverage")
coverage.setup({
  auto_reload = true,
})
```

## Expected

When I open a project without coverage, no coverage is displayed.

When I create a `coverage.out` file by running my tests, the coverage is automatically displayed.

## Details 

When I open up a project where I haven't ran code coverage I get a notification in the bottom.

![image](https://user-images.githubusercontent.com/1029947/219372971-c541806f-0469-4380-9519-e5b7bad243b1.png)

But, when I run the tests, and create the `coverage.out` file that it's expecting, the code coverage isn't automatically displayed. I have to manually run `:Coverage`.

Once I do this, the test coverage is displayed _and_ if I update the coverage file, the updates are reflected in the UI.

## Suggestion

If there's no coverage file at startup, keep checking to see if one gets added later.

Thanks for the tool. It's great!

**Comment by a-h** [comment]
That's great, thanks a lot! However, it does make me press "Enter" to get rid of the message every time I open a file in a project where I haven't ran the test suite yet.

Any chance you could make it so that if the coverage is there, show it, but otherwise, don't bother me unless I interact with the commands?

**Comment by andythigpen** [comment]
The plugin uses `vim.notify` for outputting messages so something like this could work to temporarily suppress messages.
```lua
vim.api.nvim_create_user_command("QuietCoverage", function ()
    local prev_vim_notify = vim.notify
    vim.notify = function() end
    require('coverage').load(true)
    vim.notify = prev_vim_notify
end, {})
```
Then use `:QuietCoverage` to load the coverage. Of course, that means you'd miss any error messages too but you could implement the body of your custom `vim.notify` to just ignore `vim.log.level.INFO`.
