### ISSUE TITLE
coverage report not available for file-type make

### ISSUE THREAD

**Issue by saladuit** [andythigpen/nvim-coverage#21]
My coverage report is already generate by my Makefile and located in build->report.info. I dont' quite understand how Make has anything to do with this. I'll post my configuration below and I really hope there is some simple solution for this. Can't wait to use it!
![image](https://user-images.githubusercontent.com/43225170/221362293-13def1ee-1406-4334-977f-3abc2ec635b3.png)
`:Coverage `
![image](https://user-images.githubusercontent.com/43225170/221362373-a3cf653c-3fbc-4cb6-8560-dadf63a4a6f3.png)

**Comment by saladuit** [comment]
I' saw that I had to try it on a C file. Did that and it still didn't work. I did however see a commit #18 and I'm trying to make that work.
I've just copied all of his work and just replaced cpp with c and made a new  c.lua file in coverage/languages/

**Comment by andythigpen** [comment]
Closed by #22
