### ISSUE TITLE
Automatic load

### ISSUE THREAD

**Issue by azmeuk** [andythigpen/nvim-coverage#28]
Hi, and thank you for this great plugin :clap: 

I would love `require('coverage').load()` to be automatically called when opening a file, have the coverage signs automatically loaded, and the coverage file automatically reloaded on changes.
This could probably be done with some LUA scripting, but a more generic approach could be to add a `auto_load` configuration option to load coverage data if needed on file opening. Maybe an additional `auto_toggle` option would be nice to display the signs automatically too?

What do you think?

**Comment by andythigpen** [comment]
I believe all of what you're asking for is already possible using something like:
```
require("coverage").setup({
  auto_reload = true,  -- automatically reload coverage file on changes
})

-- automatically load the coverage signs when opening a file
vim.api.nvim_create_autocmd({"BufEnter"}, {
  pattern = {"*.py"}, -- any file extension you're interested in
  callback = function() 
    -- place (show) the signs immediately after loading
    require("coverage").load(true)
  end,
})
```
