### ISSUE TITLE
Colours aren't displaying correctly with Astronvim

### ISSUE THREAD

**Issue by ewoolsey** [andythigpen/nvim-coverage#37]
All highlight bars are grey, not red or green. I'm using the example setup and installing with lazy. Not really sure how to diagnose this, but happy to provide any info you request.

```lua
  {
    "andythigpen/nvim-coverage",
    lazy = false,
    requires = "nvim-lua/plenary.nvim",
    config = function()
      require("coverage").setup {
        commands = true, -- create commands
        highlights = {
          -- customize highlight groups created by the plugin
          covered = { fg = "#75e36b" }, -- supports style, fg, bg, sp (see :h highlight-gui)
          uncovered = { fg = "#F07178" },
        },
        signs = {
          -- use your own highlight groups or text markers
          covered = { hl = "CoverageCovered", text = "▎" },
          uncovered = { hl = "CoverageUncovered", text = "▎" },
        },
        summary = {
          -- customize the summary pop-up
          min_coverage = 80.0, -- minimum coverage threshold (used for highlighting)
        },
        lang = {
          -- customize language specific settings
        },
      }
    end,
  },
```

**Comment by ewoolsey** [comment]
Not sure If this is relevant, but I'm generating coverage for Rust using Tarpaulin to create the lcov. I have `grcov` installed for the plugin but didn't use it to actually generate anything.

**Comment by FollieHiyuki** [comment]
Can you try https://github.com/andythigpen/nvim-coverage/pull/38 to see whether it fixes your issue?

Apparently `nvim-coverage` overwrites the highlight groups on setup, regardless of what they were set to before.

**Comment by andythigpen** [comment]
#38 is merged now if you want to try it in the main branch

**Comment by ewoolsey** [comment]
> #38 is merged now if you want to try it in the main branch

Doesn't seem to have fixed the issue unfortunately. Anything else I can try?

**Comment by andythigpen** [comment]
I added an autocmd to create the default highlights when the colorscheme is loaded like in this comment: https://github.com/andythigpen/nvim-coverage/issues/11#issuecomment-1460523949

Can you try the latest main branch to see if that resolves your issue?

**Comment by ewoolsey** [comment]
> I added an autocmd to create the default highlights when the colorscheme is loaded like in this comment: [#11 (comment)](https://github.com/andythigpen/nvim-coverage/issues/11#issuecomment-1460523949)
> 
> Can you try the latest main branch to see if that resolves your issue?

Success! Thanks so much :) Working as expected now, well done!
