### ISSUE TITLE
Support for Gcov

### ISSUE THREAD

**Issue by strottie** [andythigpen/nvim-coverage#43]
Is there a plan to support Gcov?

I might be inclined to give it a shot myself if one of the maintainers agrees to help.

Cheers

**Comment by andythigpen** [comment]
I don't have any plans for that, but PRs are welcome. It may be worth noting that the plugin already has support for lcov for quite a few languages, as well as a command (`CoverageLoadLcov`) and lua API (`require('coverage').load_lcov`) for any generic language that may not be explicitly supported currently. It's my understanding that lcov is built on gcov so it might already cover your use case.
