### ISSUE TITLE
[Feature Request]: Statusline info

### ISSUE THREAD

**Issue by ovidius72** [andythigpen/nvim-coverage#45]
Hi, i'd like to show coverage information of the current file in the statusline, like coverage per branch, functions and so on....
I've checked the documentation and the APIs but couldn't find an easy way to do this.
Can you please explain if that's possibile or, if not, if there's a way to obtain such information ?
Thank you.

**Comment by andythigpen** [comment]
The coverage report is cached by the plugin in the `coverage.report` module. The report generated for each language is supposed to be a `CoverageData` object (described [here](https://github.com/andythigpen/nvim-coverage/blob/aa4b4400588e2259e87e372b1e4e90ae13cf5a39/lua/coverage/languages/common.lua#L5-L23)).

For your statusline, you could use something like
```lua
local coverage_report = require('coverage.report')
if coverage_report.is_cached() then
    local report = coverage_report.get()
    -- get the current file from report.files
end
```

The `coverage.report` module and `CoverageData` object weren't meant to be part of the public API, so they may be subject to change in the future (although I'm not planning on any major changes at this time).

I hope this helps.
