### ISSUE TITLE
Link to lcov file for Rust

### ISSUE THREAD

**Issue by appelgriebsch** [andythigpen/nvim-coverage#8]
Hey,

as far as I understand the current configuration for Rust it will always run grcov when running CoverageLoad in Neovim. But I already have a lcov.info file that I want to link to.

Is that even possible?

**Comment by andythigpen** [comment]
Currently, I don't see an easy way to do that without modifying some of the code. It looks like grcov supports outputting to lcov format though and several other language implementations (dart, javascript, julia) already use that format. I can do some investigation to switch the rust implementation to use lcov, which means less code to maintain in this plugin. In addition to that, maybe adding a generic `CoverageLoadLcov <path/to/lcov.info>` command would solve this use case.

**Comment by davidbeesley** [comment]
Ran into the same issue today, would be very nice to be able to load `lcov.info` for Rust. You probably are aware of this, but it's pretty easy to use tarpaulin https://github.com/xd009642/tarpaulin to generate a lcov.info file for rust.

**Comment by andythigpen** [comment]
I haven't heard of tarpaulin before. Unfortunately, I only use Rust for one side project that I haven't devoted much time to recently. I'm willing to help out with a PR though if somebody else wants to make a first pass at switching the Rust implementation to use tarpaulin or use grcov's lcov output.
