### ISSUE TITLE
Auto update when coverage file changes

### ISSUE THREAD

**Issue by nymann** [andythigpen/nvim-coverage#9]
I don't currently think this is a feature, at least it's not auto updating for me in Python.

Currently I have another terminal window open which auto runs my unit tests when any python file changes.

Right now my work arround is the following:

Aliases
```sh
alias v="NVIM_LISTEN_ADDRESS="$(pwd)/.nvim-sock" nvim"
alias nvim-cov="ls coverage.xml | entr -c reload-nvim-coverage"
```

*reload-nvim-coverage*
```py
#!/usr/bin/env python3

from pathlib import Path
from time import sleep

from pynvim import attach


def main(path: Path):
    nvim = attach(session_type="socket", path=path)
    nvim.command("CoverageLoad")
    sleep(0.2)
    nvim.command("CoverageShow")


if __name__ == "__main__":
    main(path=Path.cwd().joinpath(".nvim-sock"))

```

Workflow
- start nvim via the `v` alias.
- then in another window (with same current working directory) `nvim-cov`

**Comment by EJahren** [comment]
As an alternative to this behavior, It could be possible to run the tests with neotest and run CoverageLoad once the process has completed. In that case it would be the responsibility of the test plugin of providing post run hooks.

**Comment by andythigpen** [comment]
I added this as a configurable option that's currently disabled by default for now. I haven't had a chance to use it thoroughly yet so I'm hesitant to turn it on for everyone out of the box. If you want to try it out, pull the latest changes and enable the `auto_reload` config option.

```
require('coverage').setup({
  auto_reload = true,
  -- optionally configure how long to wait after detecting a change to reload the file
  -- auto_reload_timeout_ms = 1000,
})
```

After that, just use `:CoverageLoad` once and it will start a file watcher that should reload the coverage report when changes are detected. Use `:CoverageClear` to turn it off.

**Comment by nymann** [comment]
Hey @andythigpen 
Thanks for implementing this feature!
Currently, it doesn't quite work in practice in Python:

Right now we are listening to changes on `.coverage`, but `.coverage` gets deleted during test execution.

In my script I was listening to changes on `coverage.xml`, but that wouldn't work for all usecases. Maybe a simple check to see if the file has been deleted don't update?

**Comment by andythigpen** [comment]
It looks like pytest deletes the file when the test runner starts and then writes it back when complete, which is problematic for long running test suites. I'm reopening this to address the issue. We can probably start a reoccurring timer that just checks until the file exists again when the file is removed.

**Comment by eivindjahren** [comment]
After looking a bit at the watch functionality, I am wondering if the best course of action is to do a `maybe_update`, ie. attempt to read the file, but if anything goes wrong, just keep the old marks. 

I also wonder if it would be better to have the watch not follow renames as it might be surprising behavior.

**Comment by andythigpen** [comment]
I merged some improvements to the main branch. There may still be issues so I'll leave this open for now.

> After looking a bit at the watch functionality, I am wondering if the best course of action is to do a `maybe_update`, ie. attempt to read the file, but if anything goes wrong, just keep the old marks.

I believe this should be the case already. The signs aren't replaced unless the callback passed to the language specific `load` function is called.

> I also wonder if it would be better to have the watch not follow renames as it might be surprising behavior.

It doesn't follow renames - libuv emits two events `change` or `rename`, but the rename event is just a delete. For more information see https://github.com/luvit/luv/blob/master/docs.md#uvfs_event_startfs_event-path-flags-callback or http://docs.libuv.org/en/v1.x/fs_event.html.

**Comment by eivindjahren** [comment]
Cool! I'll play around with it a bit this evening.

**Comment by eivindjahren** [comment]
While playing around with it I noticed that if you have more than one window, a buffers coverage annotation is updated only once it is back in focus. Otherwise, it works great!

**Comment by eivindjahren** [comment]
Having tested it for a while it seems great! I have some delay on my side which seems to be unrelated and due to vim-test.
